# Generated by Django 5.0.6 on 2024-05-30 09:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('paycheck', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('next_level_cost', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('coordinates', models.CharField(max_length=255)),
                ('emergency_index', models.SmallIntegerField()),
                ('security_index', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ResidentAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('count', models.BigIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unit', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.BigIntegerField()),
                ('cost_per_unit', models.DecimalField(decimal_places=2, max_digits=8)),
                ('icon', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=300)),
                ('img_path', models.CharField(max_length=500, null=True)),
                ('description', models.TextField()),
                ('status', models.CharField(max_length=255)),
                ('progress_points', models.IntegerField()),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.level')),
            ],
        ),
        migrations.CreateModel(
            name='ResearchAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level_name', models.IntegerField()),
                ('progress_points', models.BigIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('research', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.research')),
            ],
        ),
        migrations.CreateModel(
            name='ResourceAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('cost_per_unit', models.DecimalField(decimal_places=2, max_digits=8)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.resource')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('capacity', models.IntegerField()),
                ('object_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.object')),
            ],
        ),
        migrations.CreateModel(
            name='WorkerGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('work_start', models.CharField(max_length=255)),
                ('work_end', models.CharField(max_length=255)),
                ('object_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.object')),
            ],
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('birth_date', models.DateTimeField(auto_now_add=True)),
                ('arrival_date', models.DateTimeField(auto_now_add=True)),
                ('phone_number', models.CharField(max_length=255, null=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.job')),
                ('live_place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.room')),
                ('work_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.workergroup')),
            ],
        ),
        migrations.AddField(
            model_name='research',
            name='worker_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.workergroup'),
        ),
    ]
