# Generated by Django 5.0.6 on 2024-05-30 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_research_worker_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchaudit',
            name='research',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_audits', to='main.research'),
        ),
    ]
