# Generated by Django 5.0.6 on 2024-05-31 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_researchaudit_research'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourceaudit',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_audit', to='main.resource'),
        ),
    ]
