# Generated by Django 5.0.6 on 2024-06-01 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_resourceaudit_resource'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_allocation', models.DecimalField(decimal_places=2, max_digits=10)),
                ('daily_production', models.BigIntegerField()),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.object')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.resource')),
            ],
        ),
    ]
