# Generated by Django 5.0.6 on 2024-06-01 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_objectresource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectresource',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object', to='main.object'),
        ),
    ]
