# Generated by Django 5.0.6 on 2024-06-01 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_objectresource_object'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectresource',
            name='daily_allocation',
            field=models.DecimalField(db_default=0, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='objectresource',
            name='daily_production',
            field=models.BigIntegerField(db_default=0),
        ),
    ]
