# Generated by Django 5.0.6 on 2024-06-01 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_objectresource_daily_allocation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='object',
            name='coordinates',
        ),
        migrations.AddField(
            model_name='object',
            name='xCoordinate',
            field=models.CharField(max_length=125, null=True),
        ),
        migrations.AddField(
            model_name='object',
            name='yCoordinate',
            field=models.CharField(max_length=125, null=True),
        ),
    ]
