# Generated by Django 5.0.6 on 2024-06-01 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_object_coordinates_object_xcoordinate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='xCoordinate',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='object',
            name='yCoordinate',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
    ]
