# Generated by Django 5.0.6 on 2024-06-01 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_object_xcoordinate_alter_object_ycoordinate'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
