# Generated by Django 5.0.6 on 2024-06-02 11:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_object_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='emergency_index',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='object',
            name='xCoordinate',
            field=models.DecimalField(decimal_places=4, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='object',
            name='yCoordinate',
            field=models.DecimalField(decimal_places=4, max_digits=30, null=True),
        ),
        migrations.CreateModel(
            name='WorkDay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('work_start', models.CharField(max_length=5)),
                ('work_end', models.CharField(max_length=5)),
                ('work_group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_day', to='main.workergroup')),
            ],
        ),
    ]
