# Generated by Django 5.0.6 on 2024-06-02 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_object_emergency_index_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workday',
            name='id',
            field=models.CharField(editable=False, primary_key=True, serialize=False),
        ),
    ]
